create table products (
  id bigint generated by default as identity primary key,
  name text,
  price numeric,
  category text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
); 